version: '2'
services:
  nginx:
    container_name: server_nginx
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./src/www:/var/www
      - ./src/nginx/conf/app.conf:/etc/nginx/conf.d/app.conf
    links:
      - php
      
  php:
    container_name: server_php
    build:
      context: ./src/php-fpm
      args:
        USER_ID: ${USER_ID}
    environment:
      HTTP_PROXY: ${HTTP_PROXY}
    volumes:
      - ./src/www:/var/www
      - ./src/php-fpm/log:/var/log/php-fpm/
    expose:
      - "9000"
      
  composer:
    container_name: server_composer
    build:
      context: ./src/php-composer
      args:
        USER_ID: ${USER_ID}
        HTTP_PROXY: "${HTTP_PROXY}"
        GITHUB_OAUTH: ${GITHUB_OAUTH}
    volumes:
      - ./src/www:/app
